fixtures:
    forge_modules:
        concat:
            repo: "puppetlabs/concat"
    repositories:
        "stdlib": "https://github.com/puppetlabs/puppetlabs-stdlib"
    symlinks:
        "bind": "#{source_dir}"
