name 'thias-bind'
version '0.5.1'
source 'git://github.com/thias/puppet-bind'
author 'Matthias Saou'
license 'Apache 2.0'
summary 'BIND DNS server module'
description "Install and enable a BIND DNS server, create and manage DNS zone files."
project_page 'https://github.com/thias/puppet-bind'
dependency 'puppetlabs/concat', '>=1.0.0'
dependency 'puppetlabs/stdlib', '>=2.4.0'
