name 'cisco-bind'
version '1.0.0'
source 'git://github.com/CiscoSystems/puppet-bind'
author 'Jon Skarpeteig, Daniel Sunde'
license 'Apache 2.0'
summary 'BIND DNS server module'
description "Install and enable a BIND DNS server, create and manage DNS zone files."
project_page 'https://github.com/CiscoSystems/puppet-bind'
dependency 'puppetlabs/concat', '>=1.0.0'
dependency 'puppetlabs/stdlib', '>=2.4.0'
